# Generated by Django 6.0.6 on 2026-08-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'dashboard permission',
                'verbose_name_plural': 'dashboard permissions',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
