# Generated by Django 6.0.3 on 2026-05-16 15:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySiteMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('study_id', models.BigIntegerField()),
                ('site_id', models.BigIntegerField()),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'study site membership',
                'verbose_name_plural': 'study site memberships',
                'db_table': 'study_site_membership',
                'permissions': (),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'identity_role',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('attempt_login', models.SmallIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'identity_user',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.role')),
            ],
            options={
                'verbose_name': 'role group mapping',
                'verbose_name_plural': 'role group mappings',
                'db_table': 'identity_role_groups',
                'permissions': (),
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='identity_roles', through='identity.RoleGroup', to='auth.group'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.role')),
            ],
            options={
                'verbose_name': 'role permission mapping',
                'verbose_name_plural': 'role permission mappings',
                'db_table': 'identity_role_permissions',
                'permissions': (),
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='identity_roles', through='identity.RolePermission', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='StudyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('study_id', models.BigIntegerField()),
                ('role', models.CharField(max_length=64)),
                ('is_global_role', models.BooleanField(default=False)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='study_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'study membership',
                'verbose_name_plural': 'study memberships',
                'db_table': 'study_membership',
                'permissions': (),
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_user_roles', to='identity.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user role mapping',
                'verbose_name_plural': 'user role mappings',
                'db_table': 'identity_user_roles',
                'permissions': (),
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='identity_user_username_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='identity_user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='identity_user_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='rolegroup',
            index=models.Index(fields=['role', 'group'], name='identity_rg_role_group_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolegroup',
            unique_together={('role', 'group')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='identity_rp_role_perm_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='identity_role_name_idx'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['user', 'study_id'], name='study_mship_user_study_idx'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['study_id', 'user'], name='study_mship_study_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studymembership',
            unique_together={('user', 'study_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
