# Generated by Django 6.0.6 on 2026-08-03 11:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationTask',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('required_permission_code', models.CharField(blank=True, default='', max_length=100)),
                ('requires_training', models.BooleanField(default=False)),
                ('requires_pi_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'delegation task',
                'verbose_name_plural': 'delegation tasks',
                'db_table': 'identity_delegation_task',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.BigIntegerField()),
                ('code', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('scope_level', models.CharField(choices=[('GLOBAL', 'Global'), ('STUDY', 'Study'), ('STUDY_SITE', 'Study site')], default='STUDY_SITE', max_length=30)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'identity_role',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('attempt_login', models.SmallIntegerField(default=0)),
                ('active_session_key', models.CharField(blank=True, default='', max_length=40)),
                ('active_session_started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'identity_user',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['username'], name='identity_user_username_idx'), models.Index(fields=['email'], name='identity_user_email_idx'), models.Index(fields=['phone_number'], name='identity_user_phone_idx'), models.Index(fields=['active_session_key'], name='identity_user_session_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IdentityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=64)),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'identity permission',
                'verbose_name_plural': 'identity permissions',
                'db_table': 'identity_permission',
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['app_label', 'codename'], name='identity_perm_app_code_idx'), models.Index(fields=['codename'], name='identity_perm_code_idx')],
                'constraints': [models.UniqueConstraint(fields=('app_label', 'codename'), name='identity_permission_app_code_uq')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.identitypermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.role')),
            ],
            options={
                'verbose_name': 'role permission mapping',
                'verbose_name_plural': 'role permission mappings',
                'db_table': 'identity_role_permissions',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='identity_roles', through='identity.RolePermission', to='identity.identitypermission'),
        ),
        migrations.CreateModel(
            name='StudyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('study_id', models.BigIntegerField()),
                ('role', models.CharField(max_length=64)),
                ('is_global_role', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=30)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='study_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'study membership',
                'verbose_name_plural': 'study memberships',
                'db_table': 'study_membership',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudyMembershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField()),
                ('assigned_by_id', models.BigIntegerField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_membership_assignments', to='identity.role')),
                ('study_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='identity.studymembership')),
            ],
            options={
                'verbose_name': 'study membership role assignment',
                'verbose_name_plural': 'study membership role assignments',
                'db_table': 'study_membership_role',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudySiteMembership',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('study_id', models.BigIntegerField()),
                ('site_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=30)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='study_site_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'study site membership',
                'verbose_name_plural': 'study site memberships',
                'db_table': 'study_site_membership',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudySiteMembershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField()),
                ('assigned_by_id', models.BigIntegerField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_site_membership_assignments', to='identity.role')),
                ('study_site_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='identity.studysitemembership')),
            ],
            options={
                'verbose_name': 'study site membership role assignment',
                'verbose_name_plural': 'study site membership role assignments',
                'db_table': 'study_site_membership_role',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TrainingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.BigIntegerField()),
                ('training_code', models.CharField(max_length=100)),
                ('completed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_file_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'training completion',
                'verbose_name_plural': 'training completions',
                'db_table': 'identity_training_completion',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TrainingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.BigIntegerField()),
                ('task_code', models.CharField(blank=True, default='', max_length=64)),
                ('permission_code', models.CharField(blank=True, default='', max_length=100)),
                ('training_code', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.role')),
            ],
            options={
                'verbose_name': 'training requirement',
                'verbose_name_plural': 'training requirements',
                'db_table': 'identity_training_requirement',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_user_roles', to='identity.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user role mapping',
                'verbose_name_plural': 'user role mappings',
                'db_table': 'identity_user_roles',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DelegationOfAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_site_id', models.BigIntegerField()),
                ('task_code', models.CharField(max_length=64)),
                ('delegated_by_user_id', models.BigIntegerField()),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('signature_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'delegation of authority',
                'verbose_name_plural': 'delegations of authority',
                'db_table': 'identity_delegation_of_authority',
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', 'study_site_id', 'task_code', 'status'], name='ident_doa_usr_scope_task_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='identity_rp_role_perm_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['study_id', 'name'], name='identity_role_study_name_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='identity_role_name_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code', 'scope_level', 'version_no'], name='identity_role_scope_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['study_id', 'scope_level', 'is_active'], name='identity_role_scope_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('study_id', 'code', 'scope_level', 'version_no'), name='identity_role_study_code_scope_ver_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('study_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['user', 'study_id'], name='study_mship_user_study_idx'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['study_id', 'user'], name='study_mship_study_user_idx'),
        ),
        migrations.AddIndex(
            model_name='studymembership',
            index=models.Index(fields=['user', 'study_id', 'status'], name='study_mship_usr_scope_stat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studymembership',
            unique_together={('user', 'study_id')},
        ),
        migrations.AddIndex(
            model_name='studymembershiprole',
            index=models.Index(fields=['study_membership', 'status'], name='study_mship_role_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studymembershiprole',
            index=models.Index(fields=['role', 'status'], name='study_mship_role_stat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studymembershiprole',
            unique_together={('study_membership', 'role')},
        ),
        migrations.AddIndex(
            model_name='studysitemembership',
            index=models.Index(fields=['study_id', 'site_id', 'user_id'], name='site_mship_study_site_user_idx'),
        ),
        migrations.AddIndex(
            model_name='studysitemembership',
            index=models.Index(fields=['user_id', 'study_id', 'site_id'], name='site_mship_usr_study_site_uq'),
        ),
        migrations.AddIndex(
            model_name='studysitemembership',
            index=models.Index(fields=['user_id', 'site_id', 'status'], name='site_mship_usr_scope_stat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studysitemembership',
            unique_together={('user', 'study_id', 'site_id')},
        ),
        migrations.AddIndex(
            model_name='studysitemembershiprole',
            index=models.Index(fields=['study_site_membership', 'status'], name='site_mship_role_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studysitemembershiprole',
            index=models.Index(fields=['role', 'status'], name='site_mship_role_stat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studysitemembershiprole',
            unique_together={('study_site_membership', 'role')},
        ),
        migrations.AddIndex(
            model_name='trainingcompletion',
            index=models.Index(fields=['user', 'study_id', 'training_code'], name='identity_train_done_user_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['study_id', 'permission_code', 'is_active'], name='identity_train_req_perm_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrequirement',
            index=models.Index(fields=['study_id', 'task_code', 'is_active'], name='identity_train_req_task_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
