# Generated by Django 6.0.3 on 2026-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_membership_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'identity_role',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'role group mapping',
                'verbose_name_plural': 'role group mappings',
                'db_table': 'identity_role_groups',
                'permissions': (),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'role permission mapping',
                'verbose_name_plural': 'role permission mappings',
                'db_table': 'identity_role_permissions',
                'permissions': (),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'managed': False, 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
