CREATE TABLE IF NOT EXISTS study_eventinstance_transition_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    study_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    source_event_instance_id BIGINT NOT NULL,
    target_event_instance_id BIGINT NULL,
    transition_rule_id BIGINT NULL,
    from_event_definition_id BIGINT NOT NULL,
    to_event_definition_id BIGINT NULL,
    from_status VARCHAR(32) NOT NULL,
    to_status VARCHAR(32) NOT NULL,
    trigger_source VARCHAR(64) NOT NULL DEFAULT 'system',
    result VARCHAR(32) NOT NULL DEFAULT 'applied',
    reason VARCHAR(128) NULL,
    facts_json LONGTEXT NULL,
    created_by_id BIGINT NULL,
    updated_by_id BIGINT NULL,
    INDEX study_evtins_trlog_study_subject_created_idx (study_id, subject_id, created_at),
    INDEX study_evtins_trlog_source_created_idx (source_event_instance_id, created_at),
    INDEX study_evtins_trlog_target_created_idx (target_event_instance_id, created_at),
    INDEX study_evtins_trlog_rule_created_idx (transition_rule_id, created_at)
);
