from importlib import import_module

__all__ = [
    "BaseRandomizationImportValidationService",
    "CommitStudyRandomizationArmsImportService",
    "CommitStudyRandomizationSchemesImportService",
    "CommitStudyRandomizationSequencePeriodsImportService",
    "CreateSiteMembershipService",
    "CreateSiteService",
    "CreateStudyService",
    "DeleteRandomizationArmService",
    "DeleteRandomizationSchemeService",
    "DeleteSiteMembershipService",
    "DeleteSiteService",
    "DeleteStudyService",
    "EligibilityAssessmentService",
    "EventGateEvaluationRecorder",
    "ImportStudyCrfTemplatesTemplateService",
    "ImportStudyCrfTemplateFieldsTemplateService",
    "ImportStudyCrfValidationRulesTemplateService",
    "ImportStudyCrfSectionLayoutConfigsTemplateService",
    "ImportStudyEventDefinitionsTemplateService",
    "ImportStudyEventAttestationPoliciesTemplateService",
    "ImportStudyEventFormBindingsTemplateService",
    "ImportStudyFactMappingsTemplateService",
    "PreviewStudyRandomizationArmsImportService",
    "PreviewStudyRandomizationSchemesImportService",
    "PreviewStudyRandomizationSequencePeriodsImportService",
    "SiteAuditService",
    "StudyAuditService",
    "StudyCrfTemplateDirectoryQueryService",
    "StudyDirectoryQueryService",
    "StudyEventDefinitionDirectoryQueryService",
    "StudyFilterActiveQueryService",
    "StudyFilterInactiveQueryService",
    "StudyHistoryQueryService",
    "StudyNotFoundError",
    "StudyRandomizationDirectoryQueryService",
    "StudyRandomizationImportAuditService",
    "StudyRandomizationSlotAssignmentService",
    "StudyRandomizationSlotGenerationService",
    "StudySiteDirectoryQueryService",
    "StudySubjectCodeGenerationService",
    "StudySubjectCodeIncrementalService",
    "StudySubjectGeneratedCodes",
    "StudySubjectScreeningCodeIncrementalService",
    "ToggleStudyStatusService",
    "UpdateSiteService",
    "UpdateStudyService",
]

_MODULE_BY_NAME = {
    "BaseRandomizationImportValidationService": "apps.study.application.services.import_randomization_base",
    "CommitStudyRandomizationArmsImportService": "apps.study.application.services.import_randomization_commit",
    "CommitStudyRandomizationSchemesImportService": "apps.study.application.services.import_randomization_commit",
    "CommitStudyRandomizationSequencePeriodsImportService": "apps.study.application.services.import_randomization_commit",
    "CreateSiteMembershipService": "apps.study.application.services.site",
    "CreateSiteService": "apps.study.application.services.site",
    "CreateStudyService": "apps.study.application.services.create_study",
    "DeleteRandomizationArmService": "apps.study.application.services.delete_randomization",
    "DeleteRandomizationSchemeService": "apps.study.application.services.delete_randomization",
    "DeleteSiteMembershipService": "apps.study.application.services.site",
    "DeleteSiteService": "apps.study.application.services.site",
    "DeleteStudyService": "apps.study.application.services.delete_study",
    "EligibilityAssessmentService": "apps.study.application.services.eligibility_assessment",
    "EventGateEvaluationRecorder": "apps.study.application.services.event_gate_evaluation",
    "ImportStudyCrfTemplatesTemplateService": "apps.study.application.services.import_crf_templates_template",
    "ImportStudyCrfTemplateFieldsTemplateService": "apps.study.application.services.import_crf_template_fields_template",
    "ImportStudyCrfValidationRulesTemplateService": "apps.study.application.services.import_crf_validation_rules_template",
    "ImportStudyCrfSectionLayoutConfigsTemplateService": "apps.study.application.services.import_crf_section_layout_configs_template",
    "ImportStudyEventDefinitionsTemplateService": "apps.study.application.services.import_event_definitions_template",
    "ImportStudyEventAttestationPoliciesTemplateService": "apps.study.application.services.import_event_attestation_policies_template",
    "ImportStudyEventFormBindingsTemplateService": "apps.study.application.services.import_event_form_bindings_template",
    "ImportStudyFactMappingsTemplateService": "apps.study.application.services.import_fact_mappings_template",
    "PreviewStudyRandomizationArmsImportService": "apps.study.application.services.import_randomization_preview",
    "PreviewStudyRandomizationSchemesImportService": "apps.study.application.services.import_randomization_preview",
    "PreviewStudyRandomizationSequencePeriodsImportService": "apps.study.application.services.import_randomization_preview",
    "SiteAuditService": "apps.study.application.services.site_audit",
    "StudyAuditService": "apps.study.application.services.study_audit",
    "StudyCrfTemplateDirectoryQueryService": "apps.study.application.services.study_crf_template_directory",
    "StudyDirectoryQueryService": "apps.study.application.services.study_directory",
    "StudyEventDefinitionDirectoryQueryService": "apps.study.application.services.study_event_definition_directory",
    "StudyFilterActiveQueryService": "apps.study.application.services.study_filters",
    "StudyFilterInactiveQueryService": "apps.study.application.services.study_filters",
    "StudyHistoryQueryService": "apps.study.application.services.study_history",
    "StudyNotFoundError": "apps.study.application.services.study_directory",
    "StudyRandomizationDirectoryQueryService": "apps.study.application.services.study_randomization_directory",
    "StudyRandomizationImportAuditService": "apps.study.application.services.randomization_audit",
    "StudyRandomizationSlotAssignmentService": "apps.study.application.services.randomization_workflow",
    "StudyRandomizationSlotGenerationService": "apps.study.application.services.randomization_slot_generation",
    "StudySiteDirectoryQueryService": "apps.study.application.services.site_directory",
    "StudySubjectCodeGenerationService": "apps.study.application.services.study_subject_code_generation",
    "StudySubjectCodeIncrementalService": "apps.study.application.services.study_subject_code_generation",
    "StudySubjectGeneratedCodes": "apps.study.application.services.study_subject_code_generation",
    "StudySubjectScreeningCodeIncrementalService": "apps.study.application.services.study_subject_code_generation",
    "ToggleStudyStatusService": "apps.study.application.services.toggle_study_status",
    "UpdateSiteService": "apps.study.application.services.site",
    "UpdateStudyService": "apps.study.application.services.update_study",
}


def __getattr__(name):
    module_name = _MODULE_BY_NAME.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
