# Generated by Django 6.0.3 on 2026-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=64)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('before_data', models.TextField(default='{}')),
                ('after_data', models.TextField(default='{}')),
                ('ip_address', models.CharField(blank=True, max_length=39, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'db_table': 'audit_auditevent',
                'permissions': (),
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
