# Generated by Django 6.0.6 on 2026-08-03 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=64)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=64)),
                ('before_data', models.TextField(default='{}')),
                ('after_data', models.TextField(default='{}')),
                ('ip_address', models.CharField(blank=True, max_length=39, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_audit_events', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_audit_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'db_table': 'audit_auditevent',
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['object_type', 'object_id', 'created_at'], name='audit_auditevent_obj_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('signed_at', models.DateTimeField()),
                ('reauthenticated_at', models.DateTimeField(blank=True, null=True)),
                ('signer_name_snapshot', models.CharField(max_length=255)),
                ('signature_meaning_code', models.CharField(max_length=64)),
                ('signature_meaning_text', models.TextField()),
                ('authentication_method', models.CharField(max_length=32)),
                ('authentication_context_id', models.CharField(blank=True, max_length=128, null=True)),
                ('signed_object_type', models.CharField(max_length=64)),
                ('signed_object_id', models.CharField(max_length=64)),
                ('signed_payload_hash', models.CharField(max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=39, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_by', models.ForeignKey(db_column='signed_by_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='electronic_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'electronic signature',
                'verbose_name_plural': 'electronic signatures',
                'db_table': 'audit_electronicsignature',
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['signed_by', 'signed_at'], name='audit_esig_user_time_idx'), models.Index(fields=['signed_object_type', 'signed_object_id'], name='audit_esig_object_idx'), models.Index(fields=['signed_payload_hash'], name='audit_esig_payload_hash_idx')],
            },
        ),
    ]
