"""
Django settings for Vanguardian project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ("127.0.0.1", "localhost")),
    CSRF_TRUSTED_ORIGINS=(list, ()),
)
ENV_FILE = BASE_DIR / ".env"
if ENV_FILE.exists():
    environ.Env.read_env(ENV_FILE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", cast=str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", cast=bool)

ALLOWED_HOSTS = env("ALLOWED_HOSTS", cast=list)
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS", cast=list, default=[])

X_FRAME_OPTIONS = "SAMEORIGIN"

APPEND_SLASH = True

# Application definition

X_INSTALLED_APPS = [
    "apps.shared.apps.SharedConfig",
    "apps.audit.apps.AuditConfig",
    "apps.identity.apps.IdentityConfig",
    "apps.dashboard.apps.DashboardConfig",
    "apps.study.apps.StudyConfig",
    "apps.crf.apps.CrfConfig",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "django_tables2",
] + X_INSTALLED_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.identity.infrastructure.auth.middleware.MembershipAccessMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Vanguardian.urls"

PASSWORD_HASHERS = ["django.contrib.auth.hashers.PBKDF2PasswordHasher"]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.shared.context_processors.shared_select_options",
            ],
        },
    },
]

WSGI_APPLICATION = "Vanguardian.wsgi.application"
ASGI_APPLICATION = "Vanguardian.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
_default_sqlite_url = f"sqlite:///{(BASE_DIR / 'db.sqlite3').resolve().as_posix()}"

DATABASES = {
    "default": env.db("DATABASE_URL", default=_default_sqlite_url),
}

_raw_cache_url = env("CACHE_URL", default="")
_cache_url = (_raw_cache_url or "").strip() or "locmemcache://"
if _cache_url.startswith("memcache://"):
    # django-environ maps memcache:// to the legacy MemcachedCache backend,
    # which is removed in Django 6. Use the supported backend explicitly.
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
            "LOCATION": _cache_url.removeprefix("memcache://"),
        }
    }
else:
    CACHES = {
        "default": environ.Env.cache_url_config(_cache_url),
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("vi", _("Vietnamese")),
    ("en", _("English")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
    BASE_DIR / "node_modules",
]
STATIC_ROOT = BASE_DIR.parent / "static"

AUTH_USER_MODEL = "identity.User"
AUTHENTICATION_BACKENDS = [
    "apps.identity.infrastructure.auth.backends.IdentifierBackend",
]
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

#
# Django Tables 2
#
DJANGO_TABLES2_TEMPLATE = "shared/components/_common_tables2.html"
DJANGO_TABLES2_TABLE_ATTRS = {
    "class": "entity-table",
    "data-common-table": "true",
}
