# Generated by Django 6.0.6 on 2026-08-03 13:16

import apps.study.domain.subject_identifier_policy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='lock_subject_code_after_assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='screening_code_pattern',
            field=models.CharField(default='{study_code}-S{sequence:03d}', max_length=128),
        ),
        migrations.AddField(
            model_name='study',
            name='screening_identifier_mode',
            field=models.CharField(choices=[('generated', 'generated'), ('external', 'external'), ('disabled', 'disabled')], default=apps.study.domain.subject_identifier_policy.ScreeningIdentifierMode['GENERATED'], max_length=16),
        ),
        migrations.AddField(
            model_name='study',
            name='subject_code_pattern',
            field=models.CharField(default='{study_code}-{sequence:03d}', max_length=128),
        ),
        migrations.AddField(
            model_name='study',
            name='subject_code_uniqueness_scope',
            field=models.CharField(choices=[('study_site', 'study_site'), ('study', 'study')], default=apps.study.domain.subject_identifier_policy.SubjectCodeUniquenessScope['STUDY_SITE'], max_length=16),
        ),
        migrations.AddField(
            model_name='study',
            name='subject_identifier_mode',
            field=models.CharField(choices=[('generated_at_screening', 'generated_at_screening'), ('generated_at_enrollment', 'generated_at_enrollment'), ('copy_randomization_at_randomization', 'copy_randomization_at_randomization'), ('external', 'external')], default=apps.study.domain.subject_identifier_policy.SubjectIdentifierMode['GENERATED_AT_ENROLLMENT'], max_length=48),
        ),
    ]
