# Generated by Django 6.0.3 on 2026-06-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttestationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('study_version', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=64)),
                ('action_kind', models.CharField(choices=[('REVIEW_COMPLETION', 'Review completion'), ('CERTIFICATION', 'Certification')], max_length=32)),
                ('display_order', models.IntegerField(default=1)),
                ('statement_code', models.CharField(max_length=64)),
                ('statement_version', models.CharField(default='1', max_length=20)),
                ('required_permission_code', models.CharField(max_length=100)),
                ('required_role_code', models.CharField(blank=True, max_length=100, null=True)),
                ('delegation_task_code', models.CharField(blank=True, max_length=64, null=True)),
                ('gate_code', models.CharField(max_length=64)),
                ('requires_confirmation_checkbox', models.BooleanField(default=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('requires_reauthentication', models.BooleanField(default=False)),
                ('invalidate_on_data_change', models.BooleanField(default=True)),
                ('invalidate_on_scope_change', models.BooleanField(default=True)),
                ('is_required_for_lock', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('condition_definition', models.ForeignKey(blank=True, db_column='condition_definition_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_attestation_policies', to='study.conditiondefinition')),
                ('event_definition', models.ForeignKey(db_column='event_definition_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='attestation_policies', to='study.eventdefinition')),
                ('study', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_attestation_policies', to='study.study')),
            ],
            options={
                'verbose_name': 'study event attestation policy',
                'verbose_name_plural': 'study event attestation policies',
                'db_table': 'study_eventattestation_policy',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EventAttestationPolicyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=15)),
                ('dialog_title', models.CharField(max_length=255)),
                ('action_label', models.CharField(max_length=100)),
                ('statement_text', models.TextField()),
                ('confirmation_label', models.CharField(blank=True, max_length=255, null=True)),
                ('success_message', models.CharField(blank=True, max_length=500, null=True)),
                ('attestation_policy', models.ForeignKey(db_column='attestation_policy_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='study.eventattestationpolicy')),
            ],
            options={
                'verbose_name': 'study event attestation policy translation',
                'verbose_name_plural': 'study event attestation policy translations',
                'db_table': 'study_eventattestation_policy_translation',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EventFormDisplayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('syntax_version', models.IntegerField(default=1)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_length', models.IntegerField(default=120)),
                ('use_choice_display_label', models.BooleanField(default=True)),
                ('empty_value_policy', models.CharField(choices=[('FALLBACK', 'Fallback'), ('EMPTY_TEXT', 'Empty Text'), ('OMIT_TOKEN', 'Omit Token')], default='FALLBACK', max_length=32)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('event_form_binding', models.OneToOneField(db_column='event_form_binding_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='display_config', to='study.eventformbinding')),
            ],
            options={
                'verbose_name': 'study event form display config',
                'verbose_name_plural': 'study event form display configs',
                'db_table': 'study_eventformdisplayconfig',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EventFormDisplayConfigTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=15)),
                ('label_template', models.TextField()),
                ('fallback_template', models.TextField()),
                ('empty_value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('display_config', models.ForeignKey(db_column='display_config_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='study.eventformdisplayconfig')),
            ],
            options={
                'verbose_name': 'study event form display config translation',
                'verbose_name_plural': 'study event form display config translations',
                'db_table': 'study_eventformdisplayconfig_translation',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='eventattestationpolicy',
            index=models.Index(fields=['event_definition', 'action_kind', 'is_enabled'], name='study_evt_att_pol_evt_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattestationpolicy',
            index=models.Index(fields=['study', 'study_version', 'is_enabled'], name='study_evt_att_pol_std_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattestationpolicy',
            index=models.Index(fields=['condition_definition', 'is_enabled'], name='study_evt_att_pol_cond_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventattestationpolicy',
            constraint=models.UniqueConstraint(fields=('study', 'study_version', 'event_definition', 'code'), name='study_evt_attest_policy_scope_uniq'),
        ),
        migrations.AddIndex(
            model_name='eventattestationpolicytranslation',
            index=models.Index(fields=['language_code'], name='study_evt_att_pol_tr_lang_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventattestationpolicytranslation',
            constraint=models.UniqueConstraint(fields=('attestation_policy', 'language_code'), name='study_evt_attest_policy_trans_uniq'),
        ),
        migrations.AddConstraint(
            model_name='eventformdisplayconfig',
            constraint=models.UniqueConstraint(fields=('event_form_binding',), name='study_eventformdisplayconfig_binding_uniq'),
        ),
        migrations.AddConstraint(
            model_name='eventformdisplayconfigtranslation',
            constraint=models.UniqueConstraint(fields=('display_config', 'language_code'), name='study_eventformdisplayconfig_translation_uniq'),
        ),
    ]
