# Generated by Django 6.0.6 on 2026-08-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_study_lock_subject_code_after_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCrfPageLifecycleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('step_code', models.CharField(max_length=16)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('allowed_role_ids', models.JSONField(default=list)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('study', models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.CASCADE, related_name='crf_page_lifecycle_steps', to='study.study')),
            ],
            options={
                'db_table': 'study_crf_page_lifecycle_step',
                'ordering': ('display_order', 'id'),
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['study', 'display_order'], name='study_crf_pg_lc_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('study', 'step_code'), name='study_crf_page_lifecycle_step_uniq'), models.UniqueConstraint(fields=('study', 'display_order'), name='study_crf_page_lifecycle_order_uniq')],
            },
        ),
    ]
