# Generated by Django 6.0.6 on 2026-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_studycrfpagelifecyclestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='crf_page_lifecycle_configured',
            field=models.BooleanField(default=False),
        ),
    ]
