# Generated by Django 6.0.6 on 2026-07-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_eventattestationpolicy_invalidate_on_query_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizationscheme',
            name='master_list_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='randomizationscheme',
            name='master_list_approved_by_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='randomizationscheme',
            name='master_list_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='randomizationscheme',
            name='master_list_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='randomizationscheme',
            name='master_list_imported_by_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='randomizationscheme',
            name='master_list_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='randomizationscheme',
            name='master_list_source_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='randomizationscheme',
            name='master_list_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='randomizationslot',
            name='randomization_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='randomizationslot',
            constraint=models.UniqueConstraint(fields=('scheme', 'randomization_code'), name='study_rslot_scheme_code_uq'),
        ),
    ]
