# Generated by Django 6.0.6 on 2026-07-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_randomizationscheme_master_list_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdefinition',
            name='lifecycle_role',
            field=models.CharField(choices=[('regular', 'Regular'), ('regular_completion', 'Regular completion'), ('early_termination', 'Early termination')], default='regular', max_length=32),
        ),
    ]
