# Generated by Django 6.0.6 on 2026-08-02 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_classify_legacy_early_termination_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomizationscheme',
            name='randomization_code_padding',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='randomizationscheme',
            name='randomization_code_prefix',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
