# Generated by Django 6.0.6 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0007_randomizationscheme_randomization_code_padding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtransitionrule",
            name="auto_execute",
            field=models.BooleanField(default=False),
        ),
    ]
