# Generated by Django 6.0.3 on 2026-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceDatabaseLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='locked', max_length=16)),
                ('level', models.CharField(default='database', max_length=32)),
                ('reason', models.TextField(blank=True, null=True)),
                ('locked_at', models.DateTimeField()),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by_id', models.BigIntegerField(blank=True, null=True)),
                ('unlocked_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'governance database lock',
                'verbose_name_plural': 'governance database locks',
                'db_table': 'governance_databaselock',
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['status', 'level', 'deleted'], name='gov_dblock_status_idx'), models.Index(fields=['locked_at'], name='gov_dblock_locked_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='GovernanceLockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='locked', max_length=16)),
                ('level', models.CharField(default='page', max_length=32)),
                ('reason', models.TextField(blank=True, null=True)),
                ('subject_id', models.BigIntegerField(blank=True, null=True)),
                ('visit_id', models.BigIntegerField(blank=True, null=True)),
                ('crf_template_id', models.BigIntegerField(blank=True, null=True)),
                ('page_state_id', models.BigIntegerField(blank=True, null=True)),
                ('locked_at', models.DateTimeField()),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by_id', models.BigIntegerField(blank=True, null=True)),
                ('unlocked_by_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'governance lock record',
                'verbose_name_plural': 'governance lock records',
                'db_table': 'governance_lockrecord',
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['subject_id', 'visit_id', 'crf_template_id', 'status', 'deleted'], name='gov_lockrecord_scope_idx'), models.Index(fields=['page_state_id', 'status', 'deleted'], name='gov_lockrecord_page_idx'), models.Index(fields=['locked_at'], name='gov_lockrecord_locked_idx')],
            },
        ),
    ]
