from apps.identity.application import permissions as permission_registry

DEFAULT_PERMISSION_LABELS = permission_registry.APP_PERMISSION_LABELS
DEFAULT_EDC_PERMISSION_LABELS = permission_registry.EDC_PERMISSION_LABELS

DEFAULT_EDC_ROLES = (
    {
        "role_code": "PI",
        "role_name": "PI",
        "scope_level": "STUDY_SITE",
        "permissions": (
            "SUBJECT.VIEW",
            "CRF.VIEW",
            "QUERY.VIEW",
            "CASEBOOK.VIEW",
            "CASEBOOK.SIGN",
            "DELEGATION.VIEW",
            "DELEGATION.MANAGE",
        ),
    },
    {
        "role_code": "SITE_COORDINATOR",
        "role_name": "Site Coordinator",
        "scope_level": "STUDY_SITE",
        "permissions": (
            "SUBJECT.VIEW",
            "SUBJECT.CREATE",
            "SUBJECT.UPDATE",
            "CRF.VIEW",
            "CRF.ENTER",
            "CRF.UPDATE",
            "CRF.SUBMIT",
            "QUERY.VIEW",
            "QUERY.RESPOND",
            "VALIDATION_ISSUE.VIEW",
            "VALIDATION_ISSUE.ACKNOWLEDGE",
        ),
    },
    {
        "role_code": "CRA_MONITOR",
        "role_name": "CRA Monitor",
        "scope_level": "STUDY_SITE",
        "permissions": (
            "SUBJECT.VIEW",
            "CRF.VIEW",
            "QUERY.VIEW",
            "QUERY.CREATE",
            "QUERY.CLOSE",
            "QUERY.RETURN",
            "QUERY.CANCEL",
            "SDV.VIEW",
            "SDV.MARK",
            "SDR.MARK",
            "AUDIT_TRAIL.VIEW",
        ),
    },
    {
        "role_code": "DATA_MANAGER",
        "role_name": "Data Manager",
        "scope_level": "STUDY",
        "permissions": (
            "SUBJECT.VIEW",
            "CRF.VIEW",
            "QUERY.VIEW",
            "QUERY.CREATE",
            "QUERY.CLOSE",
            "QUERY.RETURN",
            "QUERY.CANCEL",
            "VALIDATION_ISSUE.VIEW",
            "USER_ACCESS.VIEW",
            "DATA.FREEZE",
            "DATA.LOCK",
            "DATA_EXPORT.RUN",
            "AUDIT_TRAIL.VIEW",
        ),
    },
    {
        "role_code": "STUDY_ADMIN",
        "role_name": "Study Admin",
        "scope_level": "STUDY",
        "permissions": (
            "STUDY_CONFIG.VIEW",
            "STUDY_CONFIG.MANAGE",
            "SUBJECT.VIEW",
            "CRF.VIEW",
            "CRF.UPDATE",
            "QUERY.VIEW",
            "QUERY.CREATE",
            "QUERY.RESPOND",
            "QUERY.CLOSE",
            "QUERY.RETURN",
            "QUERY.CANCEL",
            "SDV.VIEW",
            "SDV.MARK",
            "DATA.FREEZE",
            "DATA.UNFREEZE",
            "DATA.LOCK",
            "DATA.UNLOCK",
            "USER_ACCESS.VIEW",
            "USER_ACCESS.MANAGE",
            "AUDIT_TRAIL.VIEW",
            "DATA_EXPORT.RUN",
        ),
    },
)
