# Generated by Django 6.0.6 on 2026-08-03 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectIdentifierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(max_length=32)),
                ('from_value', models.CharField(blank=True, max_length=64, null=True)),
                ('to_value', models.CharField(max_length=64)),
                ('assignment_source', models.CharField(max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('related_event_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='identifier_history', to='subject.subject')),
            ],
            options={
                'verbose_name': 'subject identifier history',
                'verbose_name_plural': 'subject identifier histories',
                'db_table': 'study_subject_identifier_history',
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['subject', 'occurred_at'], name='subj_ident_hist_time_idx'), models.Index(fields=['identifier_type', 'to_value'], name='subj_ident_hist_value_idx')],
            },
        ),
    ]
