# Generated by Django 6.0.6 on 2026-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subjectidentifierhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectidentifierhistory',
            name='assignment_source',
            field=models.CharField(max_length=48),
        ),
    ]
