# Generated by Django 6.0.6 on 2026-08-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_study_lock_subject_code_after_assignment_and_more'),
        ('subject', '0003_alter_subjectidentifierhistory_assignment_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectidentifierhistory',
            name='related_event_id',
        ),
        migrations.AddField(
            model_name='subjectidentifierhistory',
            name='related_randomization_event',
            field=models.ForeignKey(blank=True, db_column='related_randomization_event_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_identifier_history_entries', to='study.randomizationevent'),
        ),
    ]
