# Generated by Django 6.0.6 on 2026-08-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_study_lock_subject_code_after_assignment_and_more"),
        (
            "subject",
            "0004_remove_subjectidentifierhistory_related_event_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectidentifierhistory",
            name="to_value",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="SubjectIdentifierMigrationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(max_length=16)),
                ("from_policy_json", models.JSONField()),
                ("to_policy_json", models.JSONField()),
                ("plan_hash", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("actor_user_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "reverses_batch",
                    models.OneToOneField(
                        blank=True,
                        db_column="reverses_batch_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rollback_batch",
                        to="subject.subjectidentifiermigrationbatch",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        db_column="study_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="subject_identifier_migration_batches",
                        to="study.study",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject identifier migration batch",
                "verbose_name_plural": "subject identifier migration batches",
                "db_table": "study_subject_identifier_migration_batch",
                "managed": True,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SubjectIdentifierMigrationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_subject_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "to_subject_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "migration_batch",
                    models.ForeignKey(
                        db_column="migration_batch_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="items",
                        to="subject.subjectidentifiermigrationbatch",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="identifier_migration_items",
                        to="subject.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject identifier migration item",
                "verbose_name_plural": "subject identifier migration items",
                "db_table": "study_subject_identifier_migration_item",
                "managed": True,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SubjectIdentifierMigrationPeriodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_kit_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "to_kit_code",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "migration_item",
                    models.ForeignKey(
                        db_column="migration_item_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="period_items",
                        to="subject.subjectidentifiermigrationitem",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        db_column="period_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="identifier_migration_items",
                        to="subject.subjectperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject identifier migration period item",
                "verbose_name_plural": "subject identifier migration period items",
                "db_table": "study_subject_identifier_migration_period_item",
                "managed": True,
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="subjectidentifiermigrationbatch",
            index=models.Index(
                fields=["study", "occurred_at"],
                name="subj_ident_mig_st_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectidentifiermigrationitem",
            constraint=models.UniqueConstraint(
                fields=("migration_batch", "subject"),
                name="subj_ident_mig_item_batch_subj_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectidentifiermigrationperioditem",
            constraint=models.UniqueConstraint(
                fields=("migration_item", "period"),
                name="subj_ident_mig_period_item_uq",
            ),
        ),
    ]
