# Generated by Django 6.0.3 on 2026-05-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crf', '0001_initial'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crffieldreviewpolicy',
            name='study',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='crf_field_review_policies', to='study.study'),
        ),
        migrations.AddField(
            model_name='crffieldreviewpolicy',
            name='field_template',
            field=models.ForeignKey(db_column='field_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_policies', to='crf.crffieldtemplate'),
        ),
        migrations.AddField(
            model_name='crffielddefinition',
            name='field_template',
            field=models.OneToOneField(db_column='field_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='definition', to='crf.crffieldtemplate'),
        ),
        migrations.AddField(
            model_name='crffieldtemplatetranslation',
            name='master',
            field=models.ForeignKey(db_column='field_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='crf.crffieldtemplate'),
        ),
        migrations.AddField(
            model_name='crffielduiconfig',
            name='field_template',
            field=models.OneToOneField(db_column='field_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ui_config', to='crf.crffieldtemplate'),
        ),
        migrations.AddField(
            model_name='crffielduiconfigtranslation',
            name='master',
            field=models.ForeignKey(db_column='field_ui_config_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='crf.crffielduiconfig'),
        ),
        migrations.AddField(
            model_name='crffieldvalidationrule',
            name='field_template',
            field=models.ForeignKey(db_column='field_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='validation_rules', to='crf.crffieldtemplate'),
        ),
        migrations.AddField(
            model_name='crffieldvalidationruletranslation',
            name='master',
            field=models.ForeignKey(db_column='field_validation_rule_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='crf.crffieldvalidationrule'),
        ),
        migrations.AddField(
            model_name='crfsectionlayoutconfig',
            name='section_template',
            field=models.OneToOneField(db_column='section_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='layout_config', to='crf.crfsectiontemplate'),
        ),
        migrations.AddField(
            model_name='crffieldtemplate',
            name='section_template',
            field=models.ForeignKey(blank=True, db_column='section_template_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_templates', to='crf.crfsectiontemplate'),
        ),
        migrations.AddField(
            model_name='crfsectiontemplatetranslation',
            name='master',
            field=models.ForeignKey(db_column='section_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='crf.crfsectiontemplate'),
        ),
        migrations.AddField(
            model_name='crftemplate',
            name='study',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='crf_templates', to='study.study'),
        ),
        migrations.AddField(
            model_name='crfsectiontemplate',
            name='crf_template',
            field=models.ForeignKey(db_column='crf_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='section_templates', to='crf.crftemplate'),
        ),
        migrations.AddField(
            model_name='crffieldtemplate',
            name='crf_template',
            field=models.ForeignKey(db_column='crf_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_templates', to='crf.crftemplate'),
        ),
        migrations.AddField(
            model_name='crffieldreviewpolicy',
            name='crf_template',
            field=models.ForeignKey(db_column='crf_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_review_policies', to='crf.crftemplate'),
        ),
        migrations.AddField(
            model_name='crftemplatetranslation',
            name='master',
            field=models.ForeignKey(db_column='crf_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='crf.crftemplate'),
        ),
        migrations.AddIndex(
            model_name='crffielddefinitiontranslation',
            index=models.Index(fields=['master'], name='crf_fdtr_master_idx'),
        ),
        migrations.AddIndex(
            model_name='crffielddefinitiontranslation',
            index=models.Index(fields=['language_code'], name='crf_fdtr_lang_idx'),
        ),
        migrations.AddConstraint(
            model_name='crffielddefinitiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='crf_fielddefinition_translation_lang_definition_uniq'),
        ),
        migrations.AddIndex(
            model_name='crffielddefinition',
            index=models.Index(fields=['field_template'], name='crf_fd_field_template_idx'),
        ),
        migrations.AddIndex(
            model_name='crffieldtemplatetranslation',
            index=models.Index(fields=['language_code', 'master'], name='crf_fttr_lang_master_idx'),
        ),
        migrations.AddIndex(
            model_name='crffieldtemplatetranslation',
            index=models.Index(fields=['master'], name='crf_ft_tr_m_idx'),
        ),
        migrations.AddIndex(
            model_name='crffieldtemplatetranslation',
            index=models.Index(fields=['language_code'], name='crf_ft_tr_l_idx'),
        ),
        migrations.AddConstraint(
            model_name='crffieldtemplatetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='crf_fieldtemplate_translation_lang_field_uniq'),
        ),
        migrations.AddIndex(
            model_name='crffielduiconfig',
            index=models.Index(fields=['field_template'], name='crf_fuic_field_tpl_idx'),
        ),
        migrations.AddIndex(
            model_name='crffielduiconfigtranslation',
            index=models.Index(fields=['master'], name='crf_fuictr_master_idx'),
        ),
        migrations.AddIndex(
            model_name='crffielduiconfigtranslation',
            index=models.Index(fields=['language_code'], name='crf_fuictr_lang_idx'),
        ),
        migrations.AddConstraint(
            model_name='crffielduiconfigtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='crf_fielduiconfig_translation_lang_config_uniq'),
        ),
        migrations.AddIndex(
            model_name='crffieldvalidationrule',
            index=models.Index(fields=['field_template'], name='crf_fvr_field_tpl_idx'),
        ),
        migrations.AddIndex(
            model_name='crffieldvalidationruletranslation',
            index=models.Index(fields=['language_code', 'master'], name='crf_fvrtr_lang_master_idx'),
        ),
        migrations.AddIndex(
            model_name='crffieldvalidationruletranslation',
            index=models.Index(fields=['master'], name='crf_fvr_tr_m_idx'),
        ),
        migrations.AddIndex(
            model_name='crffieldvalidationruletranslation',
            index=models.Index(fields=['language_code'], name='crf_fvr_tr_l_idx'),
        ),
        migrations.AddConstraint(
            model_name='crffieldvalidationruletranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='crf_fieldvalidationrule_translation_lang_rule_uniq'),
        ),
        migrations.AddIndex(
            model_name='crfsectionlayoutconfig',
            index=models.Index(fields=['section_template'], name='crf_slc_section_idx'),
        ),
        migrations.AddIndex(
            model_name='crfsectiontemplatetranslation',
            index=models.Index(fields=['language_code', 'master'], name='crf_sttr_lang_master_idx'),
        ),
        migrations.AddIndex(
            model_name='crfsectiontemplatetranslation',
            index=models.Index(fields=['master'], name='crf_st_tr_m_idx'),
        ),
        migrations.AddIndex(
            model_name='crfsectiontemplatetranslation',
            index=models.Index(fields=['language_code'], name='crf_st_tr_l_idx'),
        ),
        migrations.AddConstraint(
            model_name='crfsectiontemplatetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='crf_sectiontemplate_translation_lang_section_uniq'),
        ),
        migrations.AddIndex(
            model_name='crftemplate',
            index=models.Index(fields=['study', 'code', 'version'], name='crf_ct_study_code_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='crftemplate',
            constraint=models.UniqueConstraint(fields=('study', 'code', 'version'), name='crf_crftemplate_study_code_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='crfsectiontemplate',
            index=models.Index(fields=['crf_template', 'section_code'], name='crf_st_ct_code_idx'),
        ),
        migrations.AddIndex(
            model_name='crfsectiontemplate',
            index=models.Index(fields=['crf_template', 'display_order'], name='crf_st_ct_do_idx'),
        ),
        migrations.AddConstraint(
            model_name='crfsectiontemplate',
            constraint=models.UniqueConstraint(fields=('crf_template', 'section_code'), name='crf_sectiontemplate_crf_template_section_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='crffieldtemplate',
            index=models.Index(fields=['crf_template', 'field_key'], name='crf_ft_ct_key_idx'),
        ),
        migrations.AddIndex(
            model_name='crffieldtemplate',
            index=models.Index(fields=['section_template', 'display_order'], name='crf_ft_sec_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='crffieldtemplate',
            constraint=models.UniqueConstraint(fields=('crf_template', 'field_key'), name='crf_fieldtemplate_crf_template_fieldkey_uniq'),
        ),
        migrations.AddIndex(
            model_name='crffieldreviewpolicy',
            index=models.Index(fields=['crf_template', 'is_enabled'], name='crf_frp_crf_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='crffieldreviewpolicy',
            index=models.Index(fields=['field_template', 'review_type'], name='crf_frp_field_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='crffieldreviewpolicy',
            constraint=models.UniqueConstraint(fields=('study', 'study_version', 'crf_template', 'field_template', 'review_type'), name='crf_fieldreview_policy_scope_uniq'),
        ),
        migrations.AddIndex(
            model_name='crftemplatetranslation',
            index=models.Index(fields=['language_code', 'master'], name='crf_cttr_lang_master_idx'),
        ),
        migrations.AddIndex(
            model_name='crftemplatetranslation',
            index=models.Index(fields=['master'], name='crf_ct_tr_m_idx'),
        ),
        migrations.AddIndex(
            model_name='crftemplatetranslation',
            index=models.Index(fields=['language_code'], name='crf_ct_tr_l_idx'),
        ),
        migrations.AddConstraint(
            model_name='crftemplatetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='crf_crftemplate_translation_lang_template_uniq'),
        ),
    ]
