# Generated by Django 6.0.6 on 2026-08-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacapture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacapturepagestate',
            name='certified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datacapturepagestate',
            name='certified_by_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datacapturepagestate',
            name='certified_data_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacapturepagestate',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('correction_required', 'Correction required'), ('verified', 'Verified'), ('certified', 'Certified'), ('locked', 'Locked'), ('finalized', 'Finalized')], max_length=32),
        ),
    ]
