# Generated by Django 6.0.3 on 2026-05-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crf', '0002_initial'),
        ('datacapture', '0001_initial'),
        ('study', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacapturefactmapping',
            name='event_definition',
            field=models.ForeignKey(blank=True, db_column='event_definition_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_capture_fact_mappings', to='study.eventdefinition'),
        ),
        migrations.AddField(
            model_name='datacapturefactmapping',
            name='study',
            field=models.ForeignKey(db_column='study_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_capture_fact_mappings', to='study.study'),
        ),
        migrations.AddField(
            model_name='datacapturefieldreview',
            name='field_template',
            field=models.ForeignKey(db_column='field_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_capture_field_reviews', to='crf.crffieldtemplate'),
        ),
        migrations.AddField(
            model_name='datacapturepageentry',
            name='crf_template',
            field=models.ForeignKey(db_column='crf_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_capture_page_entries', to='crf.crftemplate'),
        ),
        migrations.AddField(
            model_name='datacapturepageentry',
            name='parent_entry',
            field=models.ForeignKey(blank=True, db_column='parent_entry_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='correction_entries', to='datacapture.datacapturepageentry'),
        ),
        migrations.AddField(
            model_name='datacapturepageentry',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_capture_page_entries', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='datacapturepageentry',
            name='visit',
            field=models.ForeignKey(db_column='visit_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_capture_page_entries', to='subject.subjecteventinstance'),
        ),
        migrations.AddField(
            model_name='datacapturepagestate',
            name='crf_template',
            field=models.ForeignKey(db_column='crf_template_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_capture_page_states', to='crf.crftemplate'),
        ),
        migrations.AddField(
            model_name='datacapturepagestate',
            name='current_entry',
            field=models.ForeignKey(blank=True, db_column='current_entry_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_for_page_states', to='datacapture.datacapturepageentry'),
        ),
        migrations.AddField(
            model_name='datacapturepagestate',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_capture_page_states', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='datacapturepagestate',
            name='visit',
            field=models.ForeignKey(db_column='visit_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_capture_page_states', to='subject.subjecteventinstance'),
        ),
        migrations.AddField(
            model_name='datacapturepageentry',
            name='page_state',
            field=models.ForeignKey(db_column='page_state_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_entries', to='datacapture.datacapturepagestate'),
        ),
        migrations.AddField(
            model_name='datacapturefieldreview',
            name='page_state',
            field=models.ForeignKey(db_column='page_state_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='field_reviews', to='datacapture.datacapturepagestate'),
        ),
        migrations.AddField(
            model_name='datacapturepagestatetransitionlog',
            name='page_state',
            field=models.ForeignKey(db_column='page_state_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transition_logs', to='datacapture.datacapturepagestate'),
        ),
        migrations.AddIndex(
            model_name='datacapturefactmapping',
            index=models.Index(fields=['study', 'study_version', 'crf_template', 'is_enabled'], name='datacapture_fact_map_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='datacapturefactmapping',
            index=models.Index(fields=['event_definition', 'is_enabled'], name='datacapture_fact_map_event_idx'),
        ),
        migrations.AddIndex(
            model_name='datacapturefactmapping',
            index=models.Index(fields=['crf_template', 'fact_key'], name='dcfm_tpl_fact_idx'),
        ),
        migrations.AddIndex(
            model_name='datacapturepagestate',
            index=models.Index(fields=['subject', 'status'], name='dcps_subject_status_idx'),
        ),
        migrations.AddIndex(
            model_name='datacapturepagestate',
            index=models.Index(fields=['visit', 'status'], name='dcps_visit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='datacapturepagestate',
            index=models.Index(fields=['crf_template', 'status'], name='dcps_crf_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='datacapturepagestate',
            constraint=models.UniqueConstraint(fields=('subject', 'visit', 'crf_template'), name='datacapture_pagestate_subject_visit_crf_uniq'),
        ),
        migrations.AddIndex(
            model_name='datacapturepageentry',
            index=models.Index(fields=['subject', 'visit', 'crf_template', 'entry_version'], name='dcpg_sub_vis_crf_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='datacapturepageentry',
            index=models.Index(fields=['page_state', 'status'], name='dcpg_pagestate_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='datacapturepageentry',
            constraint=models.UniqueConstraint(fields=('page_state', 'entry_version'), name='dcpe_pagestate_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='datacapturefieldreview',
            index=models.Index(fields=['page_state', 'status'], name='dcfr_page_status_idx'),
        ),
        migrations.AddIndex(
            model_name='datacapturefieldreview',
            index=models.Index(fields=['field_template', 'status'], name='dcfr_field_status_idx'),
        ),
        migrations.AddIndex(
            model_name='datacapturefieldreview',
            index=models.Index(fields=['page_state', 'data_version'], name='dcfr_page_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='datacapturefieldreview',
            constraint=models.UniqueConstraint(fields=('page_state', 'field_template', 'review_type'), name='datacapture_fieldreview_page_field_type_uniq'),
        ),
        migrations.AddIndex(
            model_name='datacapturepagestatetransitionlog',
            index=models.Index(fields=['page_state', 'created_at'], name='dcps_trlog_page_time_idx'),
        ),
        migrations.AddIndex(
            model_name='datacapturepagestatetransitionlog',
            index=models.Index(fields=['page_state', 'to_status'], name='dcps_trlog_page_status_idx'),
        ),
    ]
