# Generated by Django 6.0.3 on 2026-05-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crf', '0001_initial'),
        ('datacapture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconcileDataQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('import', 'Import')], max_length=16)),
                ('query_type', models.CharField(choices=[('manual', 'Manual'), ('validation', 'Validation'), ('sdv', 'SDV'), ('medical', 'Medical'), ('eligibility', 'Eligibility'), ('system', 'System')], max_length=32)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=16)),
                ('is_blocking', models.BooleanField(default=True)),
                ('question_text', models.TextField()),
                ('resolution_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('opened_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=64, null=True)),
                ('data_version', models.IntegerField(blank=True, null=True)),
                ('field_path', models.CharField(blank=True, max_length=512, null=True)),
                ('value_snapshot', models.TextField(blank=True, null=True)),
                ('assigned_to_id', models.BigIntegerField(blank=True, null=True)),
                ('opened_by_id', models.BigIntegerField(blank=True, null=True)),
                ('answered_by_id', models.BigIntegerField(blank=True, null=True)),
                ('resolved_by_id', models.BigIntegerField(blank=True, null=True)),
                ('closed_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('field_template', models.ForeignKey(blank=True, db_column='field_template_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_data_queries', to='crf.crffieldtemplate')),
                ('page_entry', models.ForeignKey(blank=True, db_column='page_entry_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_data_queries', to='datacapture.datacapturepageentry')),
                ('page_state', models.ForeignKey(db_column='page_state_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_data_queries', to='datacapture.datacapturepagestate')),
                ('validation_rule', models.ForeignKey(blank=True, db_column='validation_rule_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_data_queries', to='crf.crffieldvalidationrule')),
            ],
            options={
                'verbose_name': 'reconcile data query',
                'verbose_name_plural': 'reconcile data queries',
                'db_table': 'reconcile_dataquery',
                'managed': True,
                'default_permissions': (),
                'indexes': [models.Index(fields=['page_state'], name='recon_dq_page_state_idx'), models.Index(fields=['field_template'], name='recon_dq_field_tpl_idx'), models.Index(fields=['validation_rule'], name='recon_dq_val_rule_idx'), models.Index(fields=['status'], name='recon_dq_status_idx'), models.Index(fields=['source'], name='recon_dq_source_idx'), models.Index(fields=['page_state', 'status'], name='recon_dq_page_status_idx'), models.Index(fields=['page_state', 'is_blocking', 'status'], name='recon_dq_page_block_st_idx'), models.Index(fields=['field_template', 'status'], name='recon_dq_field_status_idx'), models.Index(fields=['assigned_to_id', 'status'], name='recon_dq_assignee_st_idx')],
            },
        ),
    ]
