# Generated by Django 6.0.6 on 2026-08-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('crf', '0002_initial'),
        ('datacapture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconcileDataQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=32)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('import', 'Import')], max_length=16)),
                ('query_type', models.CharField(choices=[('manual', 'Manual'), ('validation', 'Validation'), ('sdv', 'SDV'), ('medical', 'Medical'), ('eligibility', 'Eligibility'), ('system', 'System')], max_length=32)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=16)),
                ('is_blocking', models.BooleanField(default=True)),
                ('question_text', models.TextField()),
                ('resolution_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('opened_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=64, null=True)),
                ('data_version', models.CharField(blank=True, max_length=16, null=True)),
                ('field_path', models.CharField(blank=True, max_length=512, null=True)),
                ('value_snapshot', models.TextField(blank=True, null=True)),
                ('assigned_to_id', models.BigIntegerField(blank=True, null=True)),
                ('opened_by_id', models.BigIntegerField(blank=True, null=True)),
                ('answered_by_id', models.BigIntegerField(blank=True, null=True)),
                ('resolved_by_id', models.BigIntegerField(blank=True, null=True)),
                ('closed_by_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('field_template', models.ForeignKey(blank=True, db_column='field_template_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_data_queries', to='crf.crffieldtemplate')),
                ('page_entry', models.ForeignKey(blank=True, db_column='page_entry_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_data_queries', to='datacapture.datacapturepageentry')),
                ('page_state', models.ForeignKey(db_column='page_state_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_data_queries', to='datacapture.datacapturepagestate')),
                ('validation_rule', models.ForeignKey(blank=True, db_column='validation_rule_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_data_queries', to='crf.crffieldvalidationrule')),
            ],
            options={
                'verbose_name': 'reconcile data query',
                'verbose_name_plural': 'reconcile data queries',
                'db_table': 'reconcile_dataquery',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReconcileQueryThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('message_text', models.TextField()),
                ('message_type', models.CharField(choices=[('comment', 'Comment'), ('status_change', 'Status Change'), ('resolution', 'Resolution')], default='comment', max_length=16)),
                ('visibility', models.CharField(choices=[('site', 'Site'), ('sponsor', 'Sponsor'), ('internal', 'Internal')], default='site', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('import', 'Import')], default='manual', max_length=16)),
                ('author_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, null=True)),
                ('dataquery', models.ForeignKey(db_column='dataquery_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='query_threads', to='reconcile.reconciledataquery')),
            ],
            options={
                'verbose_name': 'reconcile query thread',
                'verbose_name_plural': 'reconcile query threads',
                'db_table': 'reconcile_query_thread',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReconcileValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('mode', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGEMENT_REQUIRED', 'Acknowledgement required'), ('ACKNOWLEDGED', 'Acknowledged'), ('CORRECTED', 'Corrected'), ('QUERY_CREATED', 'Query created'), ('CLOSED', 'Closed'), ('WAIVED', 'Waived')], max_length=50)),
                ('message', models.TextField()),
                ('failed_value', models.JSONField(blank=True, null=True)),
                ('acknowledged_by', models.BigIntegerField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_comment', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('field_instance', models.ForeignKey(blank=True, db_column='field_instance_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_validation_issues', to='datacapture.datacapturefieldentry')),
                ('form_instance', models.ForeignKey(db_column='form_instance_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_validation_issues', to='datacapture.datacapturepagestate')),
                ('rule', models.ForeignKey(db_column='rule_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_validation_issues', to='crf.crffieldvalidationrule')),
            ],
            options={
                'verbose_name': 'reconcile validation issue',
                'verbose_name_plural': 'reconcile validation issues',
                'db_table': 'reconcile_validation_issue',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReconcileValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('SUBMIT_FOR_REVIEW', 'Submit for review'), ('VALIDATION_ISSUE_ACKNOWLEDGEMENT', 'Validation issue acknowledgement')], max_length=32)),
                ('data_version', models.BigIntegerField()),
                ('triggered_by', models.BigIntegerField(blank=True, null=True)),
                ('form_instance', models.ForeignKey(db_column='form_instance_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_validation_runs', to='datacapture.datacapturepagestate')),
                ('related_audit_event', models.ForeignKey(blank=True, db_column='related_audit_event_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_validation_runs', to='audit.auditevent')),
            ],
            options={
                'verbose_name': 'reconcile validation run',
                'verbose_name_plural': 'reconcile validation runs',
                'db_table': 'reconcile_validation_run',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReconcileValidationIssueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('FAIL', 'Fail'), ('PASS', 'Pass')], max_length=16)),
                ('evaluated_values_json', models.JSONField(default=dict)),
                ('message', models.TextField()),
                ('severity', models.CharField(max_length=30)),
                ('data_version', models.BigIntegerField()),
                ('related_audit_event', models.ForeignKey(blank=True, db_column='related_audit_event_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcile_validation_issue_snapshots', to='audit.auditevent')),
                ('validation_issue', models.ForeignKey(db_column='validation_issue_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='snapshots', to='reconcile.reconcilevalidationissue')),
                ('validation_run', models.ForeignKey(db_column='validation_run_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='snapshots', to='reconcile.reconcilevalidationrun')),
            ],
            options={
                'verbose_name': 'reconcile validation issue snapshot',
                'verbose_name_plural': 'reconcile validation issue snapshots',
                'db_table': 'reconcile_validation_issue_snapshot',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='reconciledataquery',
            index=models.Index(fields=['page_state'], name='recon_dq_page_state_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciledataquery',
            index=models.Index(fields=['field_template'], name='recon_dq_field_tpl_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciledataquery',
            index=models.Index(fields=['validation_rule'], name='recon_dq_val_rule_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciledataquery',
            index=models.Index(fields=['status'], name='recon_dq_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciledataquery',
            index=models.Index(fields=['source'], name='recon_dq_source_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciledataquery',
            index=models.Index(fields=['page_state', 'status'], name='recon_dq_page_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciledataquery',
            index=models.Index(fields=['page_state', 'is_blocking', 'status'], name='recon_dq_page_block_st_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciledataquery',
            index=models.Index(fields=['field_template', 'status'], name='recon_dq_field_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciledataquery',
            index=models.Index(fields=['assigned_to_id', 'status'], name='recon_dq_assignee_st_idx'),
        ),
        migrations.AddIndex(
            model_name='reconcilequerythread',
            index=models.Index(fields=['dataquery', 'created_at'], name='recon_qthread_query_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reconcilevalidationissue',
            index=models.Index(fields=['form_instance', 'status'], name='recon_vi_form_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reconcilevalidationissue',
            index=models.Index(fields=['rule', 'form_instance', 'status'], name='recon_vi_rule_form_st_idx'),
        ),
        migrations.AddIndex(
            model_name='reconcilevalidationissue',
            index=models.Index(fields=['field_instance', 'status'], name='recon_vi_field_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reconcilevalidationrun',
            index=models.Index(fields=['form_instance', 'created_at'], name='recon_vi_run_form_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reconcilevalidationrun',
            index=models.Index(fields=['source', 'created_at'], name='recon_vi_run_source_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reconcilevalidationissuesnapshot',
            index=models.Index(fields=['validation_issue', 'created_at'], name='recon_vi_snap_issue_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reconcilevalidationissuesnapshot',
            index=models.Index(fields=['validation_run'], name='recon_vi_snap_run_idx'),
        ),
        migrations.AddIndex(
            model_name='reconcilevalidationissuesnapshot',
            index=models.Index(fields=['validation_issue', 'validation_run'], name='recon_vi_snap_issue_run_idx'),
        ),
    ]
